services:
  topic-generation-service:
    image: topic-generation-img
    container_name: topic-generation-container
    command: ["/bin/bash", "-c", "nvidia-smi; nvcc --version; python --version; echo 'Hello World'; tail -f /dev/null"]
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]